CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(60) NOT NULL,
  password_hash VARCHAR(60) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(60) UNIQUE NOT NULL,
  price VARCHAR(60) NOT NULL,
  description VARCHAR(200) NOT NULL,
  material VARCHAR(100),
  size VARCHAR(100),
  color VARCHAR(100),
  category VARCHAR(100),
  other VARCHAR(200),
  image VARCHAR(100),
  owner_id VARCHAR(36) NOT NULL,
  -- FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);